version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: axelor-postgres
    networks:
      - dokploy-network
    environment:
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
      POSTGRES_DB: axelor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axelor"]
      interval: 10s
      timeout: 5s
      retries: 5

  axelor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axelor-app
    environment:
      JAVA_OPTS: -Xms512m -Xmx1024m
      DB_URL: jdbc:postgresql://postgres:5432/axelor
      DB_USER: axelor
      DB_PASSWORD: axelor
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    networks:
      - dokploy-network  
    volumes:
      - ./data/uploads:/usr/local/tomcat/data/uploads
      - ./data/export:/usr/local/tomcat/data/export
      - ./data/indexes:/usr/local/tomcat/data/indexes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070"]
      interval: 30s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: axelor-pgadmin
    networks:
      - dokploy-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

networks:
  dokploy-network:
    external: true
    
volumes:
  postgres_data:
  pgadmin_data:
